### ISSUE TITLE
loading tags not working

### ISSUE THREAD

**Issue by JayFlowGT** [Xwilarg/NHentaiAnalytics#3]
been a while since i last used and checked this, but even after force-updating and re-adding the extension the feature seems to not work.

**Comment by Xwilarg** [comment]
Hey,
I didn't update this since a while so I'm not surprised that it's a bit broken
I'll try to look at that this week and come back to you after that

**Comment by Xwilarg** [comment]
32fb970b25287cde11b288c8517bf2ef517cde17 should fix it, I'll make a new release a bit later

**Comment by JayFlowGT** [comment]
soon ™️

**Comment by Xwilarg** [comment]
I uploaded a new version on the [release page](https://github.com/Xwilarg/NHentaiAnalytics/releases/tag/v1.2.4)
I also sent the version on the Chrome Store, it's currently being approuved

Please tell me if things are working on your side

**Comment by JayFlowGT** [comment]
seems to work 👍
